# --- 第一阶段：构建阶段 ---
FROM node:14 AS builder
WORKDIR /app
COPY web .

ENV npm_config_unsafe_perm=true
RUN npm config set registry https://registry.npmmirror.com
RUN set -euo && npm install
RUN set -euo && npm run build

# --- 第二阶段：运行阶段 ---
FROM nginx:1.27

COPY ./configs/middleware/nginx/conf.d /etc/nginx/conf.d

COPY --from=builder /app/dist /usr/share/nginx/html/aibase

CMD ["nginx", "-g", "daemon off;"]