# --- 第一阶段：构建阶段 ---
FROM golang:1.24.6-bookworm AS builder
WORKDIR /app
# 复制go.mod和go.sum文件
COPY go.mod go.sum ./

# 设置GOPROXY
ARG GOPROXY=https://goproxy.cn,direct
ENV GOPROXY=${GOPROXY}

# 下载依赖
RUN go mod download

# 复制源代码
COPY . .

RUN make build

# --- 第二阶段：运行阶段 ---
FROM alpine:3.23

WORKDIR /app

ENV ZONEINFO=/zoneinfo.zip
ENV TZ=Asia/Shanghai

COPY configs ./configs
COPY --from=builder /usr/local/go/lib/time/zoneinfo.zip /
COPY --from=builder /app/bin/ ./bin/
